[v1.29] Fix: Add Take Ownership
rancher/helm pull request #49
Opened 2024-05-15 02:01 UTC by krunalhinguu

### Updates

- `take-ownership` was missing from cmd/install.go an cmd/upgrade.go.

### Related

- https://github.com/rancher/rancher/issues/43110

2024-05-15 10:41 UTC, recena commented
❓ Do we want to continue using a fork?

2024-05-15 15:03 UTC, rohitsakala requested changes

2024-05-15 15:03 UTC, rohitsuse commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
Why are we adding TakeOwnership ? How is this being used in rancher/rancher codebase ? What change that triggered this PR ?

2024-05-15 15:27 UTC, krunalhinguu commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
https://github.com/rancher/helm/commit/d8b5b77c390af3463623faae7ed5252e322f9118

ForceAdopt was replaced with TakeOwnership, but there was no support for the tags which was removed for forceAdopt

2024-05-15 15:28 UTC, krunalhinguu commented
Didn't get you @recena

2024-05-15 16:41 UTC, kinarashah commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
@krunalhinguu you also mentioned we are running into issues with rancher/shell due to missing vars, could you post the failure/behavior you saw there?

2024-05-15 16:44 UTC, kinarashah commented
@recena This is for rancher/rancher and rancher/shell which are still using forked tags, there are additional changes existing in the fork which we're dependent on so we have to continue using fork until we establish they're no longer needed.

2024-05-15 17:00 UTC, krunalhinguu commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
So we are using forceAdopt reference in r/r, which is removed in 3.14.3, so after bumping new rancher/shell image that will become inaccessible during helm upgrade which is failing helm pods

2024-05-16 06:39 UTC, krunalhinguu commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
![Screenshot from 2024-05-16 11-32-31](https://github.com/rancher/helm/assets/25076781/1a0eba83-b337-4a67-abfa-138dca50b7ef)

@kinarashah @rohitsakala

2024-05-16 17:47 UTC, rohitsakala requested changes

2024-05-16 17:47 UTC, rohitsuse commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
@krunalhinguu This PR makes sense to me now. 


But what I don't understand is how rancher/rancher knows about --take-ownership=true flag since rancher/rancher [codebase](https://github.com/rancher/rancher/blob/release/v2.9/pkg/catalogv2/system/system.go#L54) uses FroceAdopt. Which rancher/rancher branch are you running ?

2024-05-16 17:52 UTC, krunalhinguu commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
I have updated the code in r/r and part of 1.29 release

2024-05-16 17:53 UTC, krunalhinguu commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
https://github.com/rancher/rancher/commit/2d177ae91b0574abb9dada6e2adfa5557527f969

2024-05-17 04:47 UTC, mitulshah-suse commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "take ownership will ignore the check for helm annotations and take ownership of the resources")
@rohitsakala can we please get this merged soon. It is blocking work for 1.29 support.
cc: @Sahota1225 @snasovich

2024-05-17 19:02 UTC, rohitsakala approved these changes
Didn't test the changes, but codebase looks valid.

2024-05-21 04:18 UTC, kinarashah approved these changes

2024-05-21 04:19 UTC, merged